services:
  - type: web
    name: automated-review-rating-api
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --chdir backend
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: automated-review-rating-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://automated-deployed.vercel.app"

databases:
  - name: automated-review-rating-db
    plan: free
    region: oregon
