services:
  - type: web
    name: automated-review-rating-api
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: automated-review-rating-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://automated-deployed.vercel.app"

  - type: pserv
    name: automated-review-rating-db
    env: postgres
    plan: free
    region: oregon
    ipAllowList: []
